# CGMiner-RS 软算法核心测试配置
# 此配置专门用于软算法核心测试和开发

[general]
log_level = "debug"  # 测试时使用详细日志
log_file = "/tmp/cgminer-virtual.log"
pid_file = "/tmp/cgminer-virtual.pid"
work_restart_timeout = 30  # 测试时使用较短超时
scan_time = 10  # 测试时更频繁扫描

[cores]
# 启用的核心类型列表 - 仅软算法核心
enabled_cores = ["software"]

# 默认使用的核心类型
default_core = "software"

# 软算法核心配置 (专门用于测试和开发)
[cores.software_core]
enabled = true
device_count = 2            # 测试时使用较少设备
min_hashrate = 100000000.0  # 最小算力: 100 MH/s (测试用)
max_hashrate = 500000000.0  # 最大算力: 500 MH/s (测试用)
error_rate = 0.01           # 错误率: 1% (测试时允许更高错误率)
batch_size = 1000           # 批处理大小 (测试用较小值)
work_timeout_ms = 5000      # 工作超时: 5秒 (测试时更长)

# CPU绑定配置 - 测试环境
[cores.software_core.cpu_affinity]
enabled = true              # 测试时也启用CPU绑定
strategy = "round_robin"    # 轮询策略适合测试
# manual_mapping = { 0 = 0, 1 = 1 }  # 测试时可以手动指定

# ASIC核心配置 (测试时禁用)
[cores.asic_core]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = false
power_limit = 1000.0
cooling_mode = "manual"

[devices]
auto_detect = true
scan_interval = 5  # 测试时更频繁扫描

# 测试用虚拟设备链
[[devices.chains]]
id = 0
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[[devices.chains]]
id = 1
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[pools]
strategy = "Failover"
failover_timeout = 15  # 测试时使用较短超时
retry_interval = 5

# 测试矿池配置
[[pools.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 1
enabled = true

[[pools.pools]]
url = "stratum+tcp://localhost:3333"
user = "test_user.virtual"
password = "test"
priority = 2
enabled = false  # 本地测试矿池默认禁用

[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_origins = ["*"]

[monitoring]
enabled = true
metrics_interval = 10  # 测试时更频繁收集指标
prometheus_port = 9090

[monitoring.alert_thresholds]
temperature_warning = 60.0  # 测试时使用较低阈值
temperature_critical = 70.0
hashrate_drop_percent = 30.0
error_rate_percent = 10.0  # 测试时允许更高错误率
max_temperature = 75.0
max_cpu_usage = 85.0
max_memory_usage = 80.0
max_device_temperature = 75.0
max_error_rate = 10.0
min_hashrate = 30.0
