# CGMiner-RS ASIC 设备生产配置
# 此配置专门用于 ASIC 设备的实际挖矿

[general]
log_level = "info"  # 生产环境使用标准日志级别
log_file = "/var/log/cgminer-rs/cgminer.log"
pid_file = "/var/run/cgminer-rs.pid"
work_restart_timeout = 60
scan_time = 30
device_mode = "asic"  # 仅使用 ASIC 设备

[devices.virtual]
enabled = false  # 禁用虚拟设备

[devices.asic]
enabled = true
auto_detect = true
scan_interval = 5

# 第一条链配置 (根据实际硬件调整)
[[devices.asic.chains]]
id = 0
enabled = true
frequency = 500  # 根据 ASIC 规格调整
voltage = 850    # 根据 ASIC 规格调整
auto_tune = true
chip_count = 76  # 根据实际芯片数量调整
temperature_limit = 85.0

# 第二条链配置
[[devices.asic.chains]]
id = 1
enabled = true
frequency = 500
voltage = 850
auto_tune = true
chip_count = 76
temperature_limit = 85.0

# 第三条链配置 (如果有)
[[devices.asic.chains]]
id = 2
enabled = false  # 根据实际硬件启用
frequency = 500
voltage = 850
auto_tune = true
chip_count = 76
temperature_limit = 85.0

[devices.asic.auto_tuning]
enabled = true
target_efficiency = 0.065
max_temperature = 85.0
tuning_interval = 3600
voltage_step = 25
frequency_step = 25

[pools]
strategy = "failover"
failover_timeout = 30
retry_interval = 10

[pools.asic]
# 主矿池 (替换为实际矿池地址)
[[pools.asic.pools]]
url = "stratum+tcp://pool.example.com:4444"
user = "your_username.worker1"
password = "your_password"
priority = 1
enabled = true
description = "主要生产矿池"

# 备用矿池
[[pools.asic.pools]]
url = "stratum+tcp://backup.example.com:4444"
user = "your_username.worker1"
password = "your_password"
priority = 2
enabled = true
description = "备用生产矿池"

# 第三备用矿池
[[pools.asic.pools]]
url = "stratum+tcp://pool3.example.com:4444"
user = "your_username.worker1"
password = "your_password"
priority = 3
enabled = true
description = "第三备用矿池"

[api]
enabled = true
bind_address = "0.0.0.0"  # 生产环境可能需要外部访问
port = 4028
allow_origins = ["*"]
# auth_token = "your-secret-token-here"  # 生产环境建议启用认证

[monitoring]
enabled = true
metrics_interval = 30
prometheus_port = 9090

[monitoring.alert_thresholds]
temperature_warning = 80.0
temperature_critical = 90.0
hashrate_drop_percent = 20.0
error_rate_percent = 5.0
max_temperature = 85.0
max_cpu_usage = 80.0
max_memory_usage = 90.0
max_device_temperature = 85.0
max_error_rate = 5.0
min_hashrate = 100.0
