# CGMiner-RS 默认配置文件
# 这是项目的默认配置文件，提供基本的挖矿配置
# 详细配置说明请参考: docs/configuration.md

[general]
# 日志级别: trace, debug, info, warn, error
log_level = "info"

# 日志文件路径 (可选)
log_file = "/var/log/cgminer-rs/cgminer.log"

# PID 文件路径 (可选)
pid_file = "/var/run/cgminer-rs.pid"

# 工作重启超时时间 (秒)
work_restart_timeout = 60

# 扫描时间间隔 (秒)
scan_time = 30

# 结果收集间隔 (毫秒) - 挖矿核心结果收集频率
result_collection_interval_ms = 20

# =============================================================================
# 核心配置 (默认使用软算法核心)
# =============================================================================
[cores]
# 启用的核心列表 - 使用 cgminer-cpu-btc-core
enabled_cores = ["cpu-btc"]

# 默认核心
default_core = "cpu-btc"

# CPU-BTC 核心配置 - 使用 cgminer-cpu-btc-core
[cores.cpu_btc]
enabled = true
device_count = 4             # 设备数量: 4个虚拟设备
min_hashrate = 30000000.0    # 最小算力: 30 MH/s (实际cgminer-cpu-btc-core算力)
max_hashrate = 40000000.0    # 最大算力: 40 MH/s (实际cgminer-cpu-btc-core算力)
error_rate = 0.002           # 错误率: 0.2%
batch_size = 12000           # 批处理大小: 12000
work_timeout_ms = 1500       # 工作超时: 1.5秒

# CPU绑定配置 - Mac M4 优化
[cores.cpu_btc.cpu_affinity]
enabled = false              # Mac M4: 禁用CPU绑定，依赖系统调度
strategy = "intelligent"     # 智能策略
prefer_performance_cores = true  # 优先使用性能核心

# GPU-BTC 核心配置 - 使用 cgminer-gpu-btc-core
[cores.gpu_btc]
enabled = false              # 默认禁用，需要时启用
device_count = 1             # GPU设备数量: 通常Mac只有1个GPU
max_hashrate = 1000000000000.0  # 最大算力: 1 TH/s (GPU理论算力)
work_size = 65536            # 工作组大小: Mac M4 GPU优化值
backend = "metal"            # GPU后端: metal (Mac), opencl, cuda
threads_per_threadgroup = 1024  # Metal线程组大小
work_timeout_ms = 2000       # 工作超时: 2秒

# ASIC核心配置 (默认禁用)
[cores.asic_core]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = true
power_limit = 3000.0
cooling_mode = "auto"

# =============================================================================
# 设备配置
# =============================================================================
[devices]
# 自动检测设备
auto_detect = true
# 设备扫描间隔 (秒)
scan_interval = 10

# 虚拟设备链配置
[[devices.chains]]
id = 0
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[[devices.chains]]
id = 1
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

# =============================================================================
# 矿池配置
# =============================================================================
[pools]
# 矿池策略: Failover, RoundRobin, LoadBalance, Quota
strategy = "Failover"

# 故障转移超时时间 (秒)
failover_timeout = 30

# 重试间隔 (秒)
retry_interval = 10

# F2Pool 矿池配置
[[pools.pools]]
url = "stratum+tcp://127.0.0.1:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 1
enabled = true

[[pools.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 2
enabled = true

[api]
# 启用 API 服务器
enabled = true

# 绑定地址
bind_address = "127.0.0.1"

# API 端口
port = 4028

# 允许的来源 (CORS)
allow_origins = ["*"]

[monitoring]
# 启用监控系统
enabled = true

# 指标收集间隔 (秒)
metrics_interval = 30

# Web监控界面端口 (可选)
web_port = 8888

# 告警阈值配置
[monitoring.alert_thresholds]
# 温度告警阈值 (°C)
temperature_warning = 80.0
temperature_critical = 90.0

# 算力下降告警阈值 (百分比)
hashrate_drop_percent = 20.0

# 错误率告警阈值 (百分比)
error_rate_percent = 5.0

# 其他阈值
max_temperature = 85.0
max_cpu_usage = 80.0
max_memory_usage = 90.0
max_device_temperature = 85.0
max_error_rate = 5.0
min_hashrate = 50.0

# =============================================================================
# 算力计量器配置
# =============================================================================
[hashmeter]
# 是否启用算力计量器
enabled = true
# 算力统计间隔 (秒)
interval = 5
# 日志输出间隔 (秒)
log_interval = 5
# 是否显示设备级别统计
per_device_stats = false
# 是否启用控制台输出
console_output = true
