# Cargo 构建配置文件
# 主程序基础配置，编译器优化已移至外置核心

[build]
# 使用所有CPU核心进行并行编译（注释掉让Cargo自动决定）
# jobs = 0

# 环境变量设置
[env]
# 基础编译设置（注释掉让Cargo自动决定）
# CARGO_BUILD_JOBS = { value = "0", force = false }

# 别名定义
[alias]
# 快速构建（开发用）
quick = "build --profile dev"
# 性能构建（发布用）
perf = "build --release"
# 基准测试构建
bench-build = "build --profile bench"
# 清理并重新构建
rebuild = ["clean", "build --release"]
# 运行所有测试
test-all = "test --all-features --release"

# 注册表配置
[registries]
# 使用国内镜像加速依赖下载（可选）
# crates-io = { index = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git" }

# 网络配置
[net]
# 重试次数
retry = 3
# 超时设置 (移除 timeout 配置，使用默认值)

# HTTP 配置
[http]
# 启用多路复用
multiplexing = true
# 用户代理
user-agent = "cgminer-rs-build"

# 源码替换（可选，用于加速国内构建）
# [source.crates-io]
# replace-with = "tuna"
#
# [source.tuna]
# registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

# 注意：编译器优化和平台优化已移至外置核心
# 主程序保持基础配置，由各个核心自行处理优化
