# Basic CGMiner-RS Configuration
# This is a minimal configuration for getting started with CGMiner-RS
# 适用于软算法核心 (Software Core) 的基础配置

[general]
# 日志级别: trace, debug, info, warn, error
log_level = "info"

# 日志文件路径 (可选)
log_file = "/var/log/cgminer-rs/cgminer.log"

# PID 文件路径 (可选)
pid_file = "/var/run/cgminer-rs.pid"

# 工作重启超时时间 (秒)
work_restart_timeout = 60

# 扫描时间间隔 (秒)
scan_time = 30

# =============================================================================
# 核心配置 (软算法核心配置)
# =============================================================================
[cores]
# 启用的核心类型列表 - 软算法核心适合Mac环境和开发测试
enabled_cores = ["software"]

# 默认使用的核心类型
default_core = "software"

# Bitcoin软算法核心配置 (用于CPU挖矿和开发测试)
[cores.btc_software]
enabled = true               # 启用软算法核心
device_count = 1            # 基础配置使用单个设备
min_hashrate = 30_000_000.0  # 最小算力 (H/s) - 30 MH/s
max_hashrate = 80_000_000.0  # 最大算力 (H/s) - 80 MH/s
error_rate = 0.01           # 错误率 (1%)
batch_size = 100000         # 批处理大小
work_timeout_ms = 5000      # 工作超时时间 (毫秒)

# CPU亲和性配置
[cores.btc_software.cpu_affinity]
enabled = true              # 启用CPU亲和性绑定
strategy = "round_robin"    # 轮询策略

# Maijie L7 ASIC核心配置 (基础配置中禁用)
[cores.maijie_l7]
enabled = false             # 基础配置禁用ASIC核心
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = true
power_limit = 3000.0
cooling_mode = "auto"

# =============================================================================
# 设备配置 (软算法核心设备配置)
# =============================================================================
[devices]
# 自动检测设备
auto_detect = true
# 设备扫描间隔 (秒)
scan_interval = 10

# 设备链配置 (基础配置使用单个链)
[[devices.chains]]
id = 0                     # 链ID
enabled = true             # 启用此链
frequency = 600            # 频率设置 (MHz)
voltage = 900              # 电压设置 (mV)
auto_tune = true           # 启用自动调优
chip_count = 64            # 芯片数量

# =============================================================================
# 矿池配置
# =============================================================================
[pools]
# 使用故障转移策略 - 主矿池和备用矿池
strategy = "failover"

# 故障转移超时时间 (秒)
failover_timeout = 30

# 重试间隔 (秒)
retry_interval = 30

# F2Pool 矿池配置 - 适用于软算法核心
[[pools.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 1
enabled = true
description = "F2Pool 主矿池"

# F2Pool 亚洲备用矿池
[[pools.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 2
enabled = true
description = "F2Pool 亚洲备用矿池"

[api]
# 启用 API 服务器
enabled = true

# 绑定地址 (基础配置仅本地访问)
bind_address = "127.0.0.1"

# API 端口
port = 4028

# 允许的来源 (CORS)
allow_origins = ["*"]

# 认证令牌 (基础配置可选)
# auth_token = "your-secret-token-here"

[monitoring]
# 启用监控系统
enabled = true

# 指标收集间隔 (秒)
metrics_interval = 30

# 内置Web监控端口
web_port = 8888

# 告警阈值配置
[monitoring.alert_thresholds]
# 温度告警阈值 (°C)
temperature_warning = 80.0
temperature_critical = 90.0

# 算力下降告警阈值 (百分比)
hashrate_drop_percent = 20.0

# 错误率告警阈值 (百分比)
error_rate_percent = 5.0

# 其他阈值
max_temperature = 85.0
max_cpu_usage = 80.0
max_memory_usage = 90.0
max_device_temperature = 85.0
max_error_rate = 5.0
min_hashrate = 30.0
