# CGMiner-RS 高性能配置 - 目标50+ GH/s
# 此配置专门用于达到50 GH/s以上的总算力
# 通过增加设备数量和优化参数来实现高算力目标

[general]
name = "cgminer-high-performance"
log_level = "info"
log_file = "logs/cgminer-high-performance.log"
pid_file = "/tmp/cgminer-high-performance.pid"
work_restart_timeout = 30
scan_time = 15

[mining]
algorithm = "SHA256"
difficulty_target = 0x1d00ffff
work_timeout = 45
result_timeout = 25

# =============================================================================
# 高性能软算法核心配置 - 目标50+ GH/s
# =============================================================================
[cores]
enabled_cores = ["software"]
default_core = "software"

[cores.software_core]
enabled = true
device_count = 64            # 大幅增加设备数量 (64个设备)
min_hashrate = 1000000000.0  # 最小算力: 1 GH/s per device
max_hashrate = 2000000000.0  # 最大算力: 2 GH/s per device
error_rate = 0.001           # 极低错误率: 0.1%
batch_size = 8000            # 大批次处理
work_timeout_ms = 1500       # 快速响应

# 高性能CPU绑定配置
[cores.software_core.cpu_affinity]
enabled = true
strategy = "performance_first"  # 性能优先策略
avoid_hyperthreading = false   # 利用超线程
prefer_performance_cores = true # 优先性能核心

# 禁用ASIC核心
[cores.asic_core]
enabled = false

# =============================================================================
# 高性能设备配置
# =============================================================================
[devices]
auto_detect = true
scan_interval = 30  # 减少扫描开销

# 多个高性能虚拟链配置
[[devices.chains]]
id = 0
enabled = true
frequency = 1200  # 高频率
voltage = 1000
auto_tune = false
chip_count = 4    # 增加芯片数量

[[devices.chains]]
id = 1
enabled = true
frequency = 1200
voltage = 1000
auto_tune = false
chip_count = 4

[[devices.chains]]
id = 2
enabled = true
frequency = 1200
voltage = 1000
auto_tune = false
chip_count = 4

[[devices.chains]]
id = 3
enabled = true
frequency = 1200
voltage = 1000
auto_tune = false
chip_count = 4

# =============================================================================
# 矿池配置
# =============================================================================
[pools]
strategy = "Failover"
failover_timeout = 20
retry_interval = 5

[[pools.pools]]
url = "stratum+tcp://192.168.18.240:10203"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 1
enabled = true

[[pools.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 2
enabled = false

# =============================================================================
# API配置
# =============================================================================
[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_origins = ["*"]

# =============================================================================
# 监控配置 - 适配高性能目标
# =============================================================================
[monitoring]
enabled = true
metrics_interval = 20  # 更频繁的监控
web_port = 8888  # 使用简单的内置Web监控

# 告警阈值配置 - 针对50+ GH/s目标
[monitoring.alert_thresholds]
temperature_warning = 80.0
temperature_critical = 90.0
hashrate_drop_percent = 15.0  # 更严格的算力下降阈值
error_rate_percent = 3.0      # 更严格的错误率阈值

# 高性能阈值设置
max_temperature = 85.0
max_cpu_usage = 95.0          # 允许更高CPU使用率
max_memory_usage = 90.0
max_device_temperature = 85.0
max_error_rate = 3.0
min_hashrate = 50.0           # 目标最小算力: 50 GH/s

# =============================================================================
# 性能优化配置
# =============================================================================
[performance]

# 算力优化
[performance.hashrate_optimization]
base_hashrate = 2000000000.0      # 2 GH/s基础算力
hashrate_variance = 0.1           # ±10%变化范围
frequency_hashrate_factor = 1.8   # 频率-算力因子
voltage_hashrate_factor = 1.5     # 电压-算力因子
temperature_impact_factor = 0.98  # 温度影响因子
adaptive_adjustment = true        # 自适应调整

# 内存优化
[performance.memory_optimization]
work_cache_size = 2000           # 增大工作缓存
result_cache_size = 20000        # 增大结果缓存
stats_retention_seconds = 1800   # 30分钟统计保留
enable_memory_pool = true        # 启用内存池
preallocated_memory_mb = 128     # 预分配128MB内存

# 网络优化
[performance.network_optimization]
connection_pool_size = 20        # 连接池大小
request_timeout_ms = 2000        # 请求超时
max_concurrent_requests = 50     # 最大并发请求
keepalive_interval = 30          # 保活间隔

# =============================================================================
# 日志配置
# =============================================================================
[logging]
level = "info"
file = "logs/cgminer-high-performance.log"
max_size = "200MB"
max_files = 5
console = true
json_format = false
