# CGMiner 性能优化配置文件
# 此配置文件针对高性能挖矿进行了优化

[general]
name = "cgminer-performance"
log_level = "info"
log_file = "logs/cgminer-performance.log"
pid_file = "cgminer-performance.pid"

[mining]
algorithm = "SHA256"
difficulty_target = 0x1d00ffff
work_timeout = 60
result_timeout = 30

# 软算法核心配置
[cores.software]
enabled = true
device_count = 8  # 增加设备数量以充分利用多核CPU
min_hashrate = 2000000000.0  # 2 GH/s
max_hashrate = 8000000000.0  # 8 GH/s
error_rate = 0.005  # 降低错误率到0.5%
batch_size = 2000  # 增大批次大小

# 性能优化配置
[performance]

# CPU绑定优化
[performance.cpu_affinity]
enabled = true
strategy = "intelligent"  # 智能分配策略
avoid_hyperthreading = false
prefer_performance_cores = true

# 算力优化
[performance.hashrate_optimization]
base_hashrate = 3000000000.0  # 3 GH/s 基础算力
hashrate_variance = 0.15  # ±15% 算力波动
frequency_hashrate_factor = 1.8  # 频率对算力的影响因子
voltage_hashrate_factor = 1.3   # 电压对算力的影响因子
temperature_impact_factor = 0.98  # 温度对算力的影响
adaptive_adjustment = true

# 内存优化
[performance.memory_optimization]
work_cache_size = 3000
result_cache_size = 30000
stats_retention_seconds = 7200  # 2小时
enable_memory_pool = true
preallocated_memory_mb = 128

# 线程优化
[performance.thread_optimization]
worker_threads_per_device = 1
thread_priority = "High"
thread_stack_size_kb = 512
enable_thread_pool = true

# 批处理优化
[performance.batch_optimization]
default_batch_size = 2000
min_batch_size = 500
max_batch_size = 10000
adaptive_batch_size = true
batch_timeout_ms = 800

# 矿池配置
[[pools]]
name = "f2pool"
url = "stratum+tcp://btc.f2pool.com:1314"
username = "kayuii.bbt"  # 使用优化的用户名
password = "x"
priority = 1
enabled = true

[[pools]]
name = "antpool"
url = "stratum+tcp://stratum.antpool.com:3333"
username = "kayuii.bbt"
password = "x"
priority = 2
enabled = true

# 设备配置 - 针对性能优化
[[devices]]
chain_id = 0
enabled = true
frequency = 800  # 提高频率
voltage = 1000   # 提高电压
auto_tune = false
chip_count = 64
temperature_limit = 85.0  # 提高温度限制
fan_speed = 70

[[devices]]
chain_id = 1
enabled = true
frequency = 850
voltage = 1020
auto_tune = false
chip_count = 64
temperature_limit = 85.0
fan_speed = 75

[[devices]]
chain_id = 2
enabled = true
frequency = 900
voltage = 1040
auto_tune = false
chip_count = 64
temperature_limit = 85.0
fan_speed = 80

[[devices]]
chain_id = 3
enabled = true
frequency = 950
voltage = 1060
auto_tune = false
chip_count = 64
temperature_limit = 85.0
fan_speed = 85

# API配置
[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_remote = false
api_key = "performance-mining-2024"

# WebSocket配置
[websocket]
enabled = true
bind_address = "127.0.0.1"
port = 4029

# 监控配置
[monitoring]
enabled = true
metrics_interval = 30  # 30秒收集一次指标
alert_thresholds.temperature = 80.0
alert_thresholds.hashrate_drop = 0.2  # 算力下降20%时告警
alert_thresholds.error_rate = 0.02    # 错误率超过2%时告警

# 日志配置
[logging]
level = "info"
file = "logs/cgminer-performance.log"
max_size = "100MB"
max_files = 10
console = true
json_format = false

# 性能监控配置
[performance_monitoring]
enabled = true
cpu_usage_threshold = 90.0
memory_usage_threshold = 80.0
disk_usage_threshold = 85.0
network_monitoring = true

# 自动调优配置
[auto_tuning]
enabled = true
adjustment_interval = 300  # 5分钟调整一次
max_frequency_increase = 100  # 最大频率增加100MHz
max_voltage_increase = 50     # 最大电压增加50mV
temperature_safety_margin = 5.0  # 温度安全边距5°C

# 故障恢复配置
[fault_recovery]
enabled = true
auto_restart_on_error = true
max_restart_attempts = 3
restart_delay = 30  # 30秒后重启
health_check_interval = 60  # 60秒健康检查

# 统计配置
[statistics]
enabled = true
collection_interval = 60  # 60秒收集一次统计
retention_period = 86400   # 保留24小时数据
export_format = "json"
export_path = "stats/"
