# CGMiner-RS 工作配置文件
# 与当前代码结构匹配的配置

[general]
log_level = "debug"
log_file = "logs/cgminer.log"
pid_file = "cgminer.pid"
work_restart_timeout = 60
scan_time = 30

[cores]
enabled_cores = ["btc-software"]
default_core = "btc-software"

[cores.btc_software]
enabled = true
device_count = 4
min_hashrate = 2000000000.0    # 2 GH/s
max_hashrate = 8000000000.0    # 8 GH/s
error_rate = 0.01
batch_size = 4000
work_timeout_ms = 5000

[cores.btc_software.cpu_affinity]
enabled = true
strategy = "round_robin"

[cores.maijie_l7]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = true
power_limit = 3000.0
cooling_mode = "auto"

[devices]
auto_detect = true
scan_interval = 10

[[devices.chains]]
id = 0
enabled = true
frequency = 600
voltage = 900
auto_tune = true
chip_count = 64

[[devices.chains]]
id = 1
enabled = true
frequency = 650
voltage = 920
auto_tune = true
chip_count = 64

[[devices.chains]]
id = 2
enabled = true
frequency = 700
voltage = 940
auto_tune = true
chip_count = 64

[[devices.chains]]
id = 3
enabled = true
frequency = 750
voltage = 960
auto_tune = true
chip_count = 64

[pools]
strategy = "Failover"
failover_timeout = 30
retry_interval = 10

[[pools.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.bbt"
password = "x"
priority = 1
enabled = true

[[pools.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "kayuii.bbt"
password = "x"
priority = 2
enabled = true

[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_origins = ["*"]

[monitoring]
enabled = true
metrics_interval = 30
web_port = 8888

[monitoring.alert_thresholds]
temperature_warning = 75.0
temperature_critical = 85.0
hashrate_drop_percent = 20.0
error_rate_percent = 5.0
max_temperature = 90.0
max_cpu_usage = 90.0
max_memory_usage = 80.0
max_device_temperature = 85.0
max_error_rate = 10.0
min_hashrate = 10000000.0

[web]
enabled = true
bind_address = "127.0.0.1"
port = 8080
static_path = "web/static"

[hashmeter]
enabled = true
log_interval = 30
per_device_stats = true
console_output = true
beautiful_output = true
hashrate_unit = "GH"
