# CGMiner-RS 虚拟设备测试配置
# 此配置专门用于虚拟设备测试和开发

[general]
log_level = "debug"  # 测试时使用详细日志
log_file = "/tmp/cgminer-virtual.log"
pid_file = "/tmp/cgminer-virtual.pid"
work_restart_timeout = 30  # 测试时使用较短超时
scan_time = 10  # 测试时更频繁扫描
device_mode = "virtual"  # 仅使用虚拟设备

[devices.virtual]
enabled = true
device_count = 2  # 测试时使用较少设备

[devices.virtual.config]
frequency = 600
voltage = 900
auto_tune = false
chip_count = 64
temperature_limit = 80.0
fan_speed = 50

[devices.virtual.mining]
min_hashrate = 30.0
max_hashrate = 100.0
error_rate = 0.5  # 测试时模拟更多错误
min_temperature = 35.0
max_temperature = 65.0
batch_size = 100000  # 测试时使用较小批次

[devices.asic]
enabled = false  # 禁用 ASIC 设备

[pools]
strategy = "failover"
failover_timeout = 15  # 测试时使用较短超时
retry_interval = 5

[pools.virtual]
[[pools.virtual.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "demo_user.worker1"
password = "x"
priority = 1
enabled = true
description = "F2Pool 亚洲服务器"

[[pools.virtual.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "demo_user.worker1"
password = "x"
priority = 2
enabled = true
description = "F2Pool 备用服务器"

[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_origins = ["*"]

[monitoring]
enabled = true
metrics_interval = 10  # 测试时更频繁收集指标
prometheus_port = 9090

[monitoring.alert_thresholds]
temperature_warning = 60.0  # 测试时使用较低阈值
temperature_critical = 70.0
hashrate_drop_percent = 30.0
error_rate_percent = 10.0  # 测试时允许更高错误率
power_limit_watts = 1000.0

[advanced]
work_queue_size = 100  # 测试时使用较小队列
result_queue_size = 100
batch_size = 10
worker_threads = 2  # 测试时使用较少线程
network_timeout = 15
reconnect_interval = 3
max_reconnect_attempts = 5

[logging]
format = "text"
rotation = "hourly"  # 测试时更频繁轮转
max_files = 3
max_size = "10MB"

[logging.targets]
console = true
file = true
syslog = false

[performance]
memory_pool_size = 16  # 测试时使用较少内存
zero_copy = true
batch_processing = true
io_buffer_size = 32

[web_ui]
enabled = true  # 测试时启用 Web UI
port = 8080
static_files_path = "./web"
auth_required = false

[database]
enabled = true  # 测试时启用数据库
type = "sqlite"
path = "/tmp/cgminer-virtual.db"
retention_days = 7  # 测试时保留较短时间

[notifications]
enabled = false  # 测试时禁用通知
