# CGMiner-RS F2Pool 简化配置文件

[general]
log_level = "info"
log_file = "cgminer.log"
pid_file = "cgminer.pid"
work_restart_timeout = 60
scan_time = 30

[devices]
auto_detect = true
scan_interval = 5

[[devices.chains]]
id = 0
enabled = true
frequency = 600
voltage = 850
auto_tune = true
chip_count = 64

[[devices.chains]]
id = 1
enabled = true
frequency = 600
voltage = 850
auto_tune = true
chip_count = 64

[pools]
strategy = "Failover"
failover_timeout = 30
retry_interval = 10

[[pools.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.001"
password = "21235365876986800"
priority = 1
enabled = true

[[pools.pools]]
url = "stratum+tcp://btc-asia.f2pool.com:1314"
user = "kayuii.001"
password = "21235365876986800"
priority = 2
enabled = true

[[pools.pools]]
url = "stratum+tcp://btc-euro.f2pool.com:1314"
user = "kayuii.001"
password = "21235365876986800"
priority = 3
enabled = true

[api]
enabled = true
bind_address = "127.0.0.1"
port = 4028
allow_origins = ["*"]

[monitoring]
enabled = true
metrics_interval = 30
prometheus_port = 9090

[monitoring.alert_thresholds]
temperature_warning = 75.0
temperature_critical = 85.0
hashrate_drop_percent = 20.0
error_rate_percent = 5.0
max_temperature = 85.0
max_cpu_usage = 80.0
max_memory_usage = 90.0
max_device_temperature = 85.0
max_error_rate = 5.0
min_hashrate = 50.0
