# CGMiner-RS 软算法核心离线测试配置
# 本配置用于离线测试和演示
# 不需要网络连接，使用模拟的矿池和工作

[general]
log_level = "info"
log_file = "logs/cgminer-offline.log"
pid_file = "/tmp/cgminer-rs-offline.pid"
work_restart_timeout = 60
scan_time = 30

# =============================================================================
# 软算法核心配置 - 离线测试
# =============================================================================
[cores]
enabled_cores = ["software"]
default_core = "software"

[cores.software_core]
enabled = true
device_count = 8            # 适中的设备数量
min_hashrate = 500000000.0  # 500 MH/s
max_hashrate = 2000000000.0 # 2 GH/s
error_rate = 0.005          # 0.5% 错误率
batch_size = 2000
work_timeout_ms = 3000

# CPU绑定配置
[cores.software_core.cpu_affinity]
enabled = true
strategy = "round_robin"

# 禁用ASIC核心
[cores.asic_core]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = false
power_limit = 3000.0
cooling_mode = "auto"

# =============================================================================
# 离线设备配置
# =============================================================================
[devices]
auto_detect = true
scan_interval = 30

# 多个虚拟链用于演示
[[devices.chains]]
id = 0
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[[devices.chains]]
id = 1
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[[devices.chains]]
id = 2
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

[[devices.chains]]
id = 3
enabled = true
frequency = 600
voltage = 900
auto_tune = false
chip_count = 1

# =============================================================================
# 离线矿池配置 - 使用本地模拟
# =============================================================================
[pools]
strategy = "Failover"
failover_timeout = 30
retry_interval = 10

# 本地模拟矿池
[[pools.pools]]
url = "stratum+tcp://localhost:3333"
user = "offline.test"
password = "x"
priority = 1
enabled = false  # 需要本地模拟服务器

# 模拟矿池 (用于完全离线测试)
[[pools.pools]]
url = "stratum+tcp://127.0.0.1:3334"
user = "simulation.worker"
password = "x"
priority = 2
enabled = false

# 备用在线矿池 (可选)
[[pools.pools]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.bbt"
password = "21235365876986800"
priority = 3
enabled = false  # 默认禁用在线矿池

# =============================================================================
# 离线API配置
# =============================================================================
[api]
enabled = true
bind_address = "127.0.0.1"
port = 4030                 # 独特端口
allow_origins = ["*"]

# =============================================================================
# 离线监控配置
# =============================================================================
[monitoring]
enabled = true
metrics_interval = 30
prometheus_port = 9092

[monitoring.alert_thresholds]
temperature_warning = 75.0
temperature_critical = 85.0
hashrate_drop_percent = 20.0
error_rate_percent = 3.0
max_temperature = 80.0
max_cpu_usage = 85.0
max_memory_usage = 80.0
max_device_temperature = 80.0
max_error_rate = 3.0
min_hashrate = 50.0
