# CGMiner-RS 软算法核心配置 - 32设备示例
# 此配置文件演示如何配置32个软算法设备进行挖矿

[general]
log_level = "info"
log_file = "cgminer-32devices.log"
api_port = 4028
api_bind = "0.0.0.0"

[cores]
enabled_cores = ["software"]
default_core = "software"

# 软算法核心配置 - 32个设备
[cores.software_core]
enabled = true
device_count = 32            # 32个软算法设备
min_hashrate = 500000000.0   # 最小算力: 500 MH/s
max_hashrate = 2000000000.0  # 最大算力: 2 GH/s
error_rate = 0.003           # 错误率: 0.3%
batch_size = 3000            # 批处理大小
work_timeout_ms = 2000       # 工作超时: 2秒

# CPU绑定配置 - 32设备优化
[cores.software_core.cpu_affinity]
enabled = true               # 启用CPU绑定
strategy = "round_robin"     # 轮询分配策略
# 对于32个设备，系统需要有足够的CPU核心
# 建议至少16核心CPU，每2个设备共享1个核心

# 禁用ASIC核心
[cores.asic_core]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = false
power_limit = 3000.0
cooling_mode = "auto"

[devices]
auto_detect = true
scan_interval = 10           # 32设备时使用较长的扫描间隔

[pools]
strategy = "Failover"
failover_timeout = 30
retry_interval = 10

# 主矿池
[[pools.pool]]
url = "stratum+tcp://btc.f2pool.com:1314"
user = "kayuii.bbt"
password = "x"
priority = 1

# 备用矿池
[[pools.pool]]
url = "stratum+tcp://btc.f2pool.com:25"
user = "kayuii.bbt"
password = "x"
priority = 2

[monitoring]
enabled = false              # 32设备时建议禁用复杂监控以减少开销
prometheus_port = 9090
metrics_interval = 30

[web]
enabled = true
port = 8080
bind = "0.0.0.0"

# 性能优化配置
[performance]
# 32设备时的性能优化建议
worker_threads = 16          # 工作线程数，建议为CPU核心数
io_threads = 4               # I/O线程数
memory_pool_size = 1048576   # 内存池大小 (1MB)
batch_processing = true      # 启用批处理
async_processing = true      # 启用异步处理

# 系统资源限制
[limits]
max_memory_mb = 2048         # 最大内存使用 (2GB)
max_cpu_percent = 90         # 最大CPU使用率
max_open_files = 4096        # 最大打开文件数
