# CGMiner-RS 软核最大化CPU使用配置
# 适用于专用挖矿服务器，目标是最大化CPU利用率和算力输出

[general]
log_level = "info"
log_file = "logs/cgminer-max-cpu.log"
api_port = 4028
api_bind = "0.0.0.0"

[cores]
enabled_cores = ["btc-software"]
default_core = "btc-software"

# Bitcoin软算法核心配置 - 最大化CPU使用
[cores.btc_software]
enabled = true
device_count = 64            # 大量设备数 (建议为CPU核心数的2-4倍)
min_hashrate = 2000000000.0  # 最小算力: 2 GH/s
max_hashrate = 8000000000.0  # 最大算力: 8 GH/s (高性能CPU挖矿)
error_rate = 0.001           # 极低错误率: 0.1%
batch_size = 8000            # 大批次处理提高效率
work_timeout_ms = 1500       # 快速响应时间

# CPU绑定配置 - 最大化性能
[cores.btc_software.cpu_affinity]
enabled = true               # 启用CPU绑定
strategy = "performance_first"  # 性能优先策略
avoid_hyperthreading = false   # 利用超线程提高并发
prefer_performance_cores = true # 优先使用性能核心

# 禁用ASIC核心
[cores.maijie_l7]
enabled = false

# =============================================================================
# 矿池配置 - 高性能连接
# =============================================================================
[pools]
strategy = "LoadBalance"     # 负载均衡策略
failover_timeout = 15        # 快速故障转移
retry_interval = 5           # 快速重试

[[pools.pools]]
name = "f2pool-primary"
url = "stratum+tcp://btc.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 1
enabled = true

[[pools.pools]]
name = "f2pool-backup"
url = "stratum+tcp://btc-asia.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 2
enabled = true

[[pools.pools]]
name = "antpool-backup"
url = "stratum+tcp://stratum.antpool.com:3333"
username = "kayuii.bbt"
password = "x"
priority = 3
enabled = true

# =============================================================================
# 设备配置 - 高性能优化
# =============================================================================
[devices]
auto_detect = true
scan_interval = 120          # 较长扫描间隔减少开销

# =============================================================================
# 性能优化配置
# =============================================================================
[performance]

# 算力优化 - 最大化输出
[performance.hashrate_optimization]
base_hashrate = 4000000000.0      # 4 GH/s基础算力
hashrate_variance = 0.05          # ±5%变化范围 (更稳定)
frequency_hashrate_factor = 2.0   # 高频率-算力因子
voltage_hashrate_factor = 1.8     # 高电压-算力因子
temperature_impact_factor = 0.99  # 温度影响因子
adaptive_adjustment = true        # 自适应调整

# 内存优化 - 大缓存
[performance.memory_optimization]
work_cache_size = 5000           # 大工作缓存
result_cache_size = 50000        # 大结果缓存
stats_retention_seconds = 7200   # 2小时统计保留
enable_memory_pool = true        # 启用内存池
preallocated_memory_mb = 256     # 预分配256MB内存

# 线程优化 - 高性能
[performance.thread_optimization]
worker_threads_per_device = 1    # 每设备单线程 (避免竞争)
thread_priority = "High"         # 高线程优先级
thread_stack_size_kb = 1024      # 大线程栈
enable_thread_pool = true        # 启用线程池

# 批处理优化 - 大批次
[performance.batch_optimization]
default_batch_size = 8000        # 大批次处理
min_batch_size = 2000            # 最小批次
max_batch_size = 16000           # 最大批次
adaptive_batch_size = true       # 自适应批次大小
batch_timeout_ms = 500           # 快速批次超时

# 网络优化 - 高并发
[performance.network_optimization]
connection_pool_size = 50        # 大连接池
request_timeout_ms = 1500        # 快速请求超时
max_concurrent_requests = 100    # 高并发请求
keepalive_interval = 20          # 短保活间隔

# =============================================================================
# 系统资源配置 - 最大化使用
# =============================================================================
[limits]
max_memory_mb = 8192         # 最大内存使用 (8GB)
max_cpu_percent = 95         # 最大CPU使用率 (95%)
max_open_files = 16384       # 大文件描述符限制
max_network_connections = 200 # 大网络连接数

# =============================================================================
# 监控配置
# =============================================================================
[monitoring]
enabled = true
metrics_interval = 15        # 15秒监控间隔
web_port = 8080

# 高性能阈值设置
[monitoring.thresholds]
max_temperature = 90.0       # 允许更高温度
max_cpu_usage = 98.0         # 允许极高CPU使用率
max_memory_usage = 95.0      # 允许高内存使用率
max_device_temperature = 90.0
max_error_rate = 2.0         # 允许稍高错误率
min_hashrate = 100.0         # 目标最小总算力: 100 GH/s

# =============================================================================
# 算力计量器配置
# =============================================================================
[hashmeter]
enabled = true
log_interval = 30            # 30秒算力报告
per_device_stats = false     # 禁用单设备统计减少日志
console_output = true
beautiful_output = true
hashrate_unit = "GH"         # 使用GH/s单位

# =============================================================================
# Web界面配置
# =============================================================================
[web]
enabled = true
port = 8080
bind_address = "0.0.0.0"
static_files_dir = "web/static"
template_dir = "web/templates"

# =============================================================================
# 日志配置 - 高性能优化
# =============================================================================
[logging]
level = "info"               # 信息级别日志
file = "logs/cgminer-max-cpu.log"
max_size = "500MB"           # 大日志文件
max_files = 3                # 较少日志文件数
console = true
json_format = false
rotation = "daily"

# =============================================================================
# 注意事项
# =============================================================================
# 1. 此配置适用于专用挖矿服务器
# 2. 确保系统有足够的散热能力
# 3. 监控CPU温度，避免过热
# 4. 根据实际CPU核心数调整device_count
# 5. 建议在测试环境先验证配置
# 6. 定期检查系统资源使用情况
