# CGMiner-RS 软核平衡CPU使用配置
# 适用于大多数场景，在性能和资源使用之间取得平衡

[general]
log_level = "info"
log_file = "logs/cgminer-balanced.log"
api_port = 4028
api_bind = "0.0.0.0"

[cores]
enabled_cores = ["btc-software"]
default_core = "btc-software"

# Bitcoin软算法核心配置 - 平衡配置
[cores.btc_software]
enabled = true
device_count = 16            # 中等设备数 (建议为CPU核心数的1-2倍)
min_hashrate = 1000000000.0  # 最小算力: 1 GH/s
max_hashrate = 4000000000.0  # 最大算力: 4 GH/s
error_rate = 0.005           # 平衡错误率: 0.5%
batch_size = 3000            # 中等批次处理
work_timeout_ms = 3000       # 平衡超时时间

# CPU绑定配置 - 智能分配
[cores.btc_software.cpu_affinity]
enabled = true               # 启用CPU绑定
strategy = "intelligent"     # 智能分配策略
avoid_hyperthreading = false # 利用超线程但不强制
prefer_performance_cores = true # 优先性能核心但不排斥其他核心

# 禁用ASIC核心
[cores.maijie_l7]
enabled = false

# =============================================================================
# 矿池配置 - 平衡连接
# =============================================================================
[pools]
strategy = "LoadBalance"     # 负载均衡策略
failover_timeout = 30        # 平衡故障转移时间
retry_interval = 15          # 平衡重试间隔

[[pools.pools]]
name = "f2pool-primary"
url = "stratum+tcp://btc.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 1
enabled = true

[[pools.pools]]
name = "f2pool-backup"
url = "stratum+tcp://btc-asia.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 2
enabled = true

[[pools.pools]]
name = "antpool-backup"
url = "stratum+tcp://stratum.antpool.com:3333"
username = "kayuii.bbt"
password = "x"
priority = 3
enabled = true

# =============================================================================
# 设备配置 - 平衡设置
# =============================================================================
[devices]
auto_detect = true
scan_interval = 180          # 平衡扫描间隔

# =============================================================================
# 性能优化配置 - 平衡优化
# =============================================================================
[performance]

# 算力优化 - 平衡配置
[performance.hashrate_optimization]
base_hashrate = 2500000000.0      # 2.5 GH/s基础算力
hashrate_variance = 0.15          # ±15%变化范围
frequency_hashrate_factor = 1.5   # 平衡频率-算力因子
voltage_hashrate_factor = 1.3     # 平衡电压-算力因子
temperature_impact_factor = 0.97  # 温度影响因子
adaptive_adjustment = true        # 自适应调整

# 内存优化 - 中等缓存
[performance.memory_optimization]
work_cache_size = 2000           # 中等工作缓存
result_cache_size = 20000        # 中等结果缓存
stats_retention_seconds = 3600   # 1小时统计保留
enable_memory_pool = true        # 启用内存池
preallocated_memory_mb = 64      # 预分配64MB内存

# 线程优化 - 平衡优先级
[performance.thread_optimization]
worker_threads_per_device = 1    # 每设备单线程
thread_priority = "Normal"       # 正常线程优先级
thread_stack_size_kb = 512       # 中等线程栈
enable_thread_pool = true        # 启用线程池

# 批处理优化 - 中等批次
[performance.batch_optimization]
default_batch_size = 3000        # 中等批次处理
min_batch_size = 1000            # 最小批次
max_batch_size = 6000            # 最大批次
adaptive_batch_size = true       # 自适应批次大小
batch_timeout_ms = 1000          # 平衡批次超时

# 网络优化 - 中等并发
[performance.network_optimization]
connection_pool_size = 20        # 中等连接池
request_timeout_ms = 3000        # 平衡请求超时
max_concurrent_requests = 30     # 中等并发请求
keepalive_interval = 30          # 平衡保活间隔

# =============================================================================
# 系统资源配置 - 平衡使用
# =============================================================================
[limits]
max_memory_mb = 2048         # 最大内存使用 (2GB)
max_cpu_percent = 70         # 最大CPU使用率 (70%)
max_open_files = 4096        # 中等文件描述符限制
max_network_connections = 50 # 中等网络连接数

# =============================================================================
# 监控配置 - 标准监控
# =============================================================================
[monitoring]
enabled = true
metrics_interval = 30        # 30秒监控间隔
web_port = 8080

# 平衡阈值设置
[monitoring.thresholds]
max_temperature = 80.0       # 平衡温度限制
max_cpu_usage = 75.0         # 平衡CPU使用率限制
max_memory_usage = 80.0      # 平衡内存使用率限制
max_device_temperature = 80.0
max_error_rate = 3.0         # 平衡错误率
min_hashrate = 20.0          # 目标最小总算力: 20 GH/s

# =============================================================================
# 算力计量器配置 - 标准输出
# =============================================================================
[hashmeter]
enabled = true
log_interval = 30            # 30秒算力报告
per_device_stats = false     # 禁用单设备统计
console_output = true
beautiful_output = true      # 美化输出格式
hashrate_unit = "GH"         # 使用GH/s单位

# =============================================================================
# Web界面配置 - 标准访问
# =============================================================================
[web]
enabled = true
port = 8080
bind_address = "0.0.0.0"
static_files_dir = "web/static"
template_dir = "web/templates"

# =============================================================================
# 日志配置 - 标准日志
# =============================================================================
[logging]
level = "info"               # 信息级别日志
file = "logs/cgminer-balanced.log"
max_size = "200MB"           # 中等日志文件
max_files = 3                # 中等日志文件数
console = true
json_format = false
rotation = "daily"

# =============================================================================
# 自适应调整配置
# =============================================================================
[auto_adjustment]
enabled = true               # 启用自动调整
cpu_threshold = 65.0         # CPU使用率阈值
memory_threshold = 75.0      # 内存使用率阈值
temperature_threshold = 75.0 # 温度阈值
adjustment_interval = 180    # 3分钟调整间隔

# CPU过载时的调整策略
[auto_adjustment.cpu_overload]
reduce_device_count = true   # 减少设备数量
reduce_batch_size = true     # 减少批次大小
increase_timeout = true      # 增加超时时间
max_reduction_percent = 20   # 最大减少20%

# 内存过载时的调整策略
[auto_adjustment.memory_overload]
clear_cache = true           # 清理缓存
reduce_cache_size = true     # 减少缓存大小
force_gc = true              # 强制垃圾回收

# 温度过高时的调整策略
[auto_adjustment.temperature_overload]
reduce_hashrate = true       # 降低算力目标
increase_work_timeout = true # 增加工作超时
reduce_frequency = true      # 降低频率

# =============================================================================
# 动态扩展配置
# =============================================================================
[dynamic_scaling]
enabled = true               # 启用动态扩展
min_devices = 8              # 最小设备数
max_devices = 32             # 最大设备数
scale_up_threshold = 50.0    # 扩展阈值 (CPU使用率)
scale_down_threshold = 30.0  # 收缩阈值 (CPU使用率)
scale_interval = 300         # 5分钟扩展检查间隔

# =============================================================================
# 使用场景说明
# =============================================================================
# 此配置适用于以下场景：
# 1. 个人挖矿设备
# 2. 小型挖矿农场
# 3. 开发和测试环境
# 4. 需要平衡性能和稳定性的场景
# 5. 系统资源有限但希望获得合理算力的场景
#
# 配置特点：
# - 中等资源使用，不会过度占用系统
# - 智能CPU绑定，自动优化性能
# - 自适应调整，根据系统状态动态优化
# - 动态扩展，根据负载自动调整设备数量
# - 全面监控，及时发现和处理问题
