# CGMiner-RS 软核最大化CPU使用配置 (修复版)
# 移除了所有虚假配置，只保留真正被代码使用的配置项
# 适用于专用挖矿服务器，目标是最大化CPU利用率和算力输出

[general]
log_level = "info"
log_file = "logs/cgminer-max-cpu.log"
work_restart_timeout = 60
scan_time = 30

[cores]
enabled_cores = ["btc-software"]
default_core = "btc-software"

# Bitcoin软算法核心配置 - 最大化CPU使用
[cores.btc_software]
enabled = true
device_count = 64            # 大量设备数 (建议为CPU核心数的2-4倍)
min_hashrate = 2000000000.0  # 最小算力: 2 GH/s
max_hashrate = 8000000000.0  # 最大算力: 8 GH/s (高性能CPU挖矿)
error_rate = 0.001           # 极低错误率: 0.1%
batch_size = 8000            # 大批次处理提高效率
work_timeout_ms = 1500       # 快速响应时间

# CPU绑定配置 - 最大化性能
[cores.btc_software.cpu_affinity]
enabled = true               # 启用CPU绑定
strategy = "performance_first"  # 性能优先策略
avoid_hyperthreading = false   # 利用超线程提高并发
prefer_performance_cores = true # 优先使用性能核心

# 禁用ASIC核心
[cores.maijie_l7]
enabled = false
chain_count = 3
spi_speed = 6000000
uart_baud = 115200
auto_detect = false
power_limit = 3000.0
cooling_mode = "auto"

# =============================================================================
# 矿池配置 - 高性能连接
# =============================================================================
[pools]
strategy = "LoadBalance"     # 负载均衡策略
failover_timeout = 15        # 快速故障转移
retry_interval = 5           # 快速重试

[[pools.pools]]
name = "f2pool-primary"
url = "stratum+tcp://btc.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 1
enabled = true

[[pools.pools]]
name = "f2pool-backup"
url = "stratum+tcp://btc-asia.f2pool.com:1314"
username = "kayuii.bbt"
password = "x"
priority = 2
enabled = true

[[pools.pools]]
name = "antpool-backup"
url = "stratum+tcp://stratum.antpool.com:3333"
username = "kayuii.bbt"
password = "x"
priority = 3
enabled = true

# =============================================================================
# 设备配置 - 高性能优化
# =============================================================================
[devices]
auto_detect = true
scan_interval = 120          # 较长扫描间隔减少开销

# =============================================================================
# API配置 - 修复配置位置
# =============================================================================
[api]
enabled = true
bind_address = "0.0.0.0"
port = 4028

# =============================================================================
# 监控配置
# =============================================================================
[monitoring]
enabled = true
metrics_interval = 15        # 15秒监控间隔
web_port = 8080

# 高性能阈值设置
[monitoring.alert_thresholds]
temperature_warning = 85.0
temperature_critical = 95.0
hashrate_drop_percent = 20.0
error_rate_percent = 2.0
max_temperature = 90.0
max_cpu_usage = 98.0
max_memory_usage = 95.0
max_device_temperature = 90.0
max_error_rate = 2.0
min_hashrate = 100.0         # 目标最小总算力: 100 GH/s

# =============================================================================
# 算力计量器配置
# =============================================================================
[hashmeter]
enabled = true
log_interval = 30            # 30秒算力报告
per_device_stats = false     # 禁用单设备统计减少日志
console_output = true
beautiful_output = true
hashrate_unit = "GH"         # 使用GH/s单位

# =============================================================================
# Web界面配置
# =============================================================================
[web]
enabled = true
port = 8080
bind_address = "0.0.0.0"
static_path = "web/static"

# =============================================================================
# 配置说明
# =============================================================================
# 
# 此配置文件已移除所有虚假配置项，只保留真正被代码使用的配置。
# 
# 移除的虚假配置包括：
# - [performance] 整个配置块 (代码中未使用)
# - [limits] 整个配置块 (代码中未使用)  
# - [logging] 整个配置块 (代码中未使用)
# 
# 修复的配置问题：
# - 将 api_port 和 api_bind 移动到 [api] 部分
# - 修复 web 配置字段名称
# - 修复 monitoring.thresholds 字段名称
# 
# 注意事项：
# 1. 此配置适用于专用挖矿服务器
# 2. 确保系统有足够的散热能力
# 3. 监控CPU温度，避免过热
# 4. 根据实际CPU核心数调整device_count
# 5. 建议在测试环境先验证配置
# 6. 定期检查系统资源使用情况
# 
# 性能建议：
# - 16核心以上系统：device_count = 32-64
# - 8-16核心系统：device_count = 16-32  
# - 8核心以下系统：device_count = 8-16
# 
# 启动命令：
# ./target/release/cgminer-rs --config examples/configs/software_core_max_cpu_fixed.toml
